Repository fusionjs/fusion-plugin-apollo-server, pull requests merged in 2019-01, with the labels that each got.

#54 Add a default for the graphql endpoint
  README.md
  src/server.js
Labels: feature

#55 Set default apollo context to fusion ctx
  src/server.js
Labels: feature

#57 Update dependencies
  package.json
  src/server.js
  yarn.lock
Labels: bugfix

#58 Release v1.2.0-1
  package.json
Labels: release

#59 Move the apollo handler call into the upstream
  flow-typed/globals.js
  src/__tests__/server.node.js
  src/server.js
Labels: bugfix

#60 Release v1.2.0-2
  package.json
Labels: release

#64 Release v1.2.0-4
  package.json
Labels: release

#65 Release v1.2.0
  package.json
Labels: release
